name: Build Docker image

on:
    push:

jobs:
    build:
        # https://github.com/dotnet/core/issues/3309#issuecomment-543963771
        runs-on: ubuntu-16.04

        steps:
            - uses: actions/checkout@v1
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag j2ghz/gtnh-viewer
            - name: Tag image
              run: docker tag j2ghz/gtnh-viewer docker.pkg.github.com/j2ghz/gtnh-viewer/master
            - name: Push image
              run: docker push docker.pkg.github.com/j2ghz/gtnh-viewer/master
